fix: Add missing i18n import in AutoPassTimer.tsx
Error: Property 'i18n' doesn't exist at line 115
Cause: i18n was used but not imported

Fixed: Added import i18n from '../../i18n'